locals {
  tideways_api_key          = ""
  default_credentials_token = ""
  payone_credentials        = ""
  broker_api_user           = "spryker"
  broker_api_user_password  = "<template:change_me>"
  broker_user               = "spryker"
  broker_user_password      = "<template:change_me>"
  blackfire_server_id       = ""
  blackfire_server_token    = ""
  rabbitmq_default_user     = "spryker"
  rabbitmq_default_pass     = "<template:change_me>"
  oneagent_script_url       = ""
  oneagent_download_token   = ""
  aop_authentication        = "<template:change_me>"
}
