kind: services
specs:
  yves:
    cpu_limit: 1099
    memory_limit: 1099
    network_mode: test
    scheduling_strategy: test
    desired_count: 2
    health_check_grace_period_seconds: 22
    deployment_maximum_percent: 22
    deployment_minimum_healthy_percent: 22
    autoscaling_enabled: false
    autoscaling_min_capacity: 22
    autoscaling_max_capacity: 22
    load_balancer_type: test
    deregistration_delay: 22
    logs_expire: 22
  boffice:
    cpu_limit: 2099
    memory_limit: 2099
    network_mode: test1
    scheduling_strategy: test1
    desired_count: 21
    health_check_grace_period_seconds: 221
    deployment_maximum_percent: 221
    deployment_minimum_healthy_percent: 221
    autoscaling_enabled: false
    autoscaling_min_capacity: 221
    autoscaling_max_capacity: 221
    load_balancer_type: test1
    deregistration_delay: 221
    logs_expire: 221
  glue:
    cpu_limit: 1099
    memory_limit: 1099
    network_mode: test2
    scheduling_strategy: test2
    desired_count: 22
    health_check_grace_period_seconds: 222
    deployment_maximum_percent: 222
    deployment_minimum_healthy_percent: 222
    autoscaling_enabled: false
    autoscaling_min_capacity: 222
    autoscaling_max_capacity: 222
    load_balancer_type: test2
    deregistration_delay: 222
    logs_expire: 222
  mportal:
    cpu_limit: 1111
    memory_limit: 1111
    network_mode: test3
    scheduling_strategy: test3
    desired_count: 33
    health_check_grace_period_seconds: 333
    deployment_maximum_percent: 333
    deployment_minimum_healthy_percent: 333
    autoscaling_min_capacity: 333
    autoscaling_max_capacity: 333
    deregistration_delay: 333
    logs_expire: 333